swagger: '2.0'
info:
 version: 'Hvst-1.4.0:RD-R1-Tst-0.0.3'
 title: "FAIR Metrics Domain Specific - RD-R1 Metadata contains ORDO and HPO terms"
 x-tests_metric: 'https://w3id.org/rd-fairmetrics/RD-R1'
 description: >-
   A domain-specific test for metadata describing records in the Rare Disease domain.  It tests if the metadata contains annotations conforming to the Human Phenotype Ontology URLs or the Orphanet Rare Disease Ontology URLs.  One or more of either of these annotations, as the object of any triple, will be sufficient to pass the test.
 x-applies_to_principle: "R1"
 contact:
  x-organization: "EJP-RD & ELIXIR Metrics for Rare Disease"
  url: "https://github.com/LUMC-BioSemantics/RD-FAIRmetrics"
  name: 'Mark D Wilkinson'
  x-role: "responsible developer"
  email: markw@illuminae.com
  x-id: '0000-0001-6960-357X'
host: w3id.org/rd-fairness-tests
basePath: /tests/
schemes:
  - https
paths:
 rd_metadata_ordo_hpo:
  post:
   parameters:
    - name: content
      in: body
      required: true
      schema:
        $ref: '#/definitions/schemas'
   consumes:
     - application/json
   produces:
     - application/json
   responses:
     "200":
       description: >-
        The response is a binary (1/0), success or failure
definitions:
  schemas:
    required:
     - subject
    properties:
        subject:
          type: string
          description: >-
            the GUID being tested
